-- CRIE UMA TRIGGER CHAMADA ATUALIZAR_QTD_ESTOQUE 
-- QUE, SEMPRE QUE UMA NOVA VENDA FOR INSERIDA NA 
-- TABELA VENDAS, ATUALIZE A QUANTIDADE DISPONÍVEL 
-- DO PRODUTO VENDIDO NA TABELA PRODUTOS
CREATE
OR REPLACE FUNCTION ATT_QTD() RETURNS TRIGGER AS $ $ BEGIN
UPDATE
    PRODUTOS('QUANTIDADE')(
        SELECT
            (IV.QUANTIDADE - 1)
        FROM
            ITENS_VENDA AS IV
            JOIN VENDAS AS V ON V.VENDA_ID = NEW.VENDA_ID
    ) RETURN NEW;

END;

$ $ LANGUAGE PLPGSQL;

CREATE
OR REPLACE TRIGGER ATUALIZAR_QTD_ESTOQUE ON VENDAS
AFTER
INSERT
    ON VENDAS
    FOR EACH ROW EXECUTE FUNCTION ATT_QTD();