-- CRIE UMA TRIGGER CHAMADA VERIFICAR_LIMITE_VENDAS 
-- QUE, ANTES DE INSERIR UMA NOVA VENDA NA TABELA 
-- VENDAS, VERIFIQUE SE O VALOR TOTAL DA VENDA NÃO 
-- EXCEDE UM DETERMINADO LIMITE
CREATE
OR REPLACE FUNCTION CHECK_TOTAL() RETURNS TRIGGER AS $ $ DECLARE LIMITE NUMERIC := 10000;

BEGIN
SELECT
    VALOR_TOTAL
FROM
    VENDAS CASE
        WHEN(NEW.VALOR_TOTAL > LIMITE) RAISE EXCEPTION 'VALOR INSERIDO EXCEDE O LIMITE ESTABELECIDO'.RETURN NEW;

END;

$ $ LANGUAGE PLPGSQL;

CREATE
OR REPLACE TRIGGER VERIFICAR_LIMITE_VENDAS BEFORE
INSERT
    ON VENDAS FOR EACH ROW EXECUTE FUNCTION CHECK_TOTAL(LIMITE);