-- CRIE UMA TRIGGER CHAMADA ULTIMA_COMPRA_CLIENTE 
-- QUE, SEMPRE QUE UMA NOVA VENDA FOR INSERIDA NA 
-- TABELA VENDAS, ATUALIZE A DATA DA ÚLTIMA COMPRA 
-- DO CLIENTE CORRESPONDENTE NA TABELA CLIENTES.
CREATE
OR REPLACE FUNCTION UDT_DATA() RETURNS TRIGGER AS $ $ BEGIN
UPDATE
    CLIENTES('ULTIMA_COMPRA')
SET
    (NOW())
WHERE
    CLIENTE_ID = NEW.CLIENTE_ID;

RETURN NEW;

END;

$ $ LANGUAGE PLPGSQL;

CREATE
OR REPLACE TRIGGER ULTIMA_COMPRA_CLIENTE
AFTER
INSERT
    ON VENDAS FOR EACH ROW EXECUTE FUNCTION UPT_DATA();