-- CRIE UMA FUNÇÃO CHAMADA 
-- CALCULAR_MEDIA_VENDAS QUE RETORNA A MÉDIA DE 
-- VALOR TOTAL DE TODAS AS VENDAS
CREATE
OR REPLACE FUNCTION CALCUAR_MEDIA_VENDAS() RETURNS NUMERIC AS $ $ DELCARE MEDIA NUMERIC;

BEGIN
SELECT
    AVG(VALOR_TOTAL) INTO MEDIA
FROM
    VENDAS
END;

RETURN MEDIA;

$ $ LANGUAGE PLPGSQL;