-- CRIE UMA TRIGGER QUE INSIRA AUTOMATICAMENTE A DATA E HORA NA TABELA LOGS
-- SEMPRE QUE UMA NOVA LINHA FOR INSERIDA, ATUALIZADA OU DELETADA NA TABELA
-- ALUNOS
CREATE
OR REPLACE FUNCTION UP_LOG_DATE() RETURNS TRIGGER AS $ $ DECLARE OP VARCHAR(10);

BEGIN IF(TG_OP = 'INSERT') THEN OP := 'INSERIR';

ELSE IF (TG_OP = 'UPDATE') THEN OP := 'UPDATE';

ELSE IF (TG_OP = 'DELETE' THEN OP := 'DELETE');

END IF;

INSERT INTO
    LOGS (ACAO, TABELA, DATA_HORA)
VALUES
    (OP, 'ALUNOS', NOW());

RETURN NEW;

END;

$ $ LANGUAGE PLPGSQL;

CREATE
OR REPLACE TRIGGER DATE_LOG_TRIGGER
AFTER
INSERT
    OR DELETE
    OR
UPDATE
    ON ALUNOS FOR EACH ROW EXECUTE FUNCTION EXEC_LOG_DATE();