-- CRIE UMA TRIGGER QUE IMPEÇA A EXCLUSÃO DE UM CURSO SE HOUVER ALUNOS
-- MATRICULADOS NELE, REGISTRANDO UM LOG DE TENTATIVA DE EXCLUSÃO NA TABELA LOGS
CREATE
OR REPLACE FUNCTION CUE() RETURNS TRIGGER AS $ $ DECLARE FLAG_ALUNO NUMERIC;

BEGIN
SELECT
    COUNT(M.ID_ALUNO) INTO FLAG_ALUNO
FROM
    MATRICULA AS M
WHERE
    M.ID_CURSO = OLD.ID_CURSO;

IF (FLAG_ALUNO > 0) THEN
INSERT INTO
    LOGS(ACAO, TABELA, DATA_HORA)
VALUES
    ('DELETE', 'CURSOS', NOW());

RAISE EXCEPTION 'NÃO É POSSÍVEL EXCLUIR O CURSO POIS HÁ ALUNOS MATRICULADOS'
END IF;

RETURN OLD;

END;

$ $ LANGUAGE PLPGSQL;

CREATE
OR REPLACE TRIGGER STALL BEFORE DELETE ON CURSOS FOR EACH ROW EXECUTE FUNCTION CUE();