-- CRIE UMA TRIGGER QUE CALCULE AUTOMATICAMENTE A MÉDIA DAS NOTAS DO ALUNO
-- SEMPRE QUE UMA NOVA NOTA FOR INSERIDA NA TABELA NOTA. LEMBRE-SE DE
-- ATUALIZAR NOSSO MODELO DE DADOS, INCLUINDO A COLUNA MÉDIA.
ALTER TABLE
    NOTA
ADD
    COLUMN MEDIA NUMERIC;

CREATE
OR REPLACE FUNCTION CALC_AVG () RETURNS TRIGGER AS $ $ DECLARE CURRENT NUMERIC;

MEDIA NUMERIC;

FLAG_PF NUMERIC;

BEGIN MEDIA := 0;

FLAG_PF := 0;

N.NOTA
FROM
    NOTAS FOR FLAG_PF LOOP IF N.NOTA = NULL THEN CURRENT := 0
END IF;

MEDIA := MEDIA + CURRENT IF FLAG_PF = 2 THEN MEDIA := MEDIA - CURRENT MEDIA := MEDIA / 2
END LOOP;

END IF;

INSERT
    ON NOTA(MEDIA)
VALUES
(MEDIA)
WHERE
    N.MATRICULA = NEW.MATRICULA;

RETURN NEW;

END;

$ $ LANGUAGE PLPGSQL;

CREATE
OR REPLACE TRIGGER TRIGGER_MEDIA
AFTER
INSERT
    ON NOTA FOR EACH ROW EXECUTE FUNCTION CALC_AVG;