-- CRIE UMA TRIGGER QUE CALCULE AUTOMATICAMENTE A MÉDIA DAS NOTAS DO ALUNO
-- SEMPRE QUE UMA NOVA NOTA FOR INSERIDA NA TABELA NOTA. LEMBRE-SE DE
-- ATUALIZAR NOSSO MODELO DE DADOS, INCLUINDO A COLUNA MÉDIA.
ALTER TABLE
    NOTA
ADD
    COLUMN MEDIA NUMERIC;

CREATE
OR REPLACE FUNCTION CALC_AVG () RETURNS TRIGGER AS $ $ BEGIN
INSERT
    INTO NOTAS(MEDIA)
SELECT
    AVG(N.NOTA)
FROM
    NOTAS AS N
WHERE
    N.ID_MATRICULA = NEW.ID_MATRICULA RETURN NEW;

END;

$ $ LANGUAGE PLPGSQL;

CREATE
OR REPLACE TRIGGER TRIGGER_MEDIA
AFTER
INSERT
    ON NOTA FOR EACH ROW EXECUTE FUNCTION CALC_AVG();