-- CRIE UMA TRIGGER QUE IMPEÇA A INSERÇÃO DE UMA NOVA MATRÍCULA SE O ALUNO JÁ
-- ESTIVER MATRICULADO NO MESMO CURSO,REGISTRANDO UM LOG NA TABELA LOGS.

CREATE OR REPLACE FUNCTION CHECK_DB_MATRICULA() RETURNS TRIGGER AS 
$$
BEGIN
    IF EXISTS(
        SELECT 1 FROM MATRICULA AS M 
        WHERE M.ID_CURSO = NEW.ID_CURSO AND M.ID_ALUNO = NEW.ID_ALUNO
        ) THEN 
            INSERT INTO LOGS(ACAO, TABELA, DATA_HORA) VALUES('INSERT', 'MATRICULA', NOW());
            RAISE EXCEPTION 'INSERÇÃO INTERROMPIDA! ALUNO JÁ MATRICULADO NO CURSO';
    END IF
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE TRIGGER DOUBLE_MATRICULA 
BEFORE INSERT ON MATRICULA 
FOR EACH ROW
EXECUTE FUNCTION CHECK_DB_MATRICULA();