-- CRIE UMA VIEW QUE LISTE O NOME E A MATRÍCULA DOS ALUNOS QUE OBTIVERAM NOTA
-- ACIMA DE 7.0 NA P1
CREATE VIEW APROVADOS AS
SELECT
    A.NOME,
    A.MATRICULA
FROM
    MATRICULA AS M
    JOIN ALUNOS A ON A.ID = M.ID_ALUNO
    JOIN NOTA AS N ON N.ID_MATRICULA = M.ID
WHERE
    N.TIPO_PROVA = 'P1'
    AND N.NOTA > 7