-- CRIE UMA FUNCTION QUE RETORNE A MÉDIA DE NOTAS DE TODOS OS ALUNOS EM UM
-- CURSO
CREATE
OR REPLACE FUNCTION MEDIA(COURSE_ID INTEGER) RETURNS NUMERIC AS $ $ DECLARE MEDIA NUMERIC;

BEGIN
SELECT
    AVG(N.NOTA) INTO MEDIA
FROM
    MATRICULA AS M
    JOIN NOTA AS N ON N.ID_MATRICULA = M.ID
WHERE
    M.ID_CURSO = COURSE_ID
END;

$ $ LANGUAGE PLPGSQL;