-- CRIE UMA PROCEDURE UMA QUE PERCORRA TODAS AS MATRICULAS E VERIFIQUE AS
-- NOTAS DOS ALUNOS, CASO AS NOTAS DA P1 + P2 SOMADAS SEJAM MAIOR QUE 7 ,
-- MUDE O STATUS DA TABELA MATRÍCULA PARA 'APROVADO', SE FOR MAIOR QUE 5 MUDE
-- PARA 'EM PROVA FINAL', CASO CONTRÁRIO 'REPROVADO'. LEMBRE-SE DE CRIAR O ALTER
-- TABLE DA TABELA MATRICULA PARA ADICIONAR A COLUNA STATUS. PARA TREINARMOS,
-- FAÇA A QUESTÃO USANDO CURSOR.
CREATE TYPE STAT_SIT ENUM AS ('APROVADO', 'REPROVADO', 'EM PROVA FINAL');

ALTER TABLE
    MATRICULA
ADD
    COLUMN STAT_SIT SITUACAO;

CREATE OR REPLACE PROCEDURE CHECK_MAT() AS 
$ $ 
DECLARE CURSOR_NOTAS CURSOR FOR
SELECT
    N.NOTA
FROM
    NOTA AS N
    JOIN MATRICULA AS M ON M.ID = N.ID_MATRICULA
    ORDER BY n.tipo_prova;
CHECK_PF NUMERIC;
CURRENT NUMERIC;
OVERALL NUMERIC;

 PF NUMERIC;

BEGIN 

OVERALL := 0;
CHECK_PF := 0;

OPEN CURSOR_NOTAS;

LOOP FETCH NEXT
FROM
    CURSOR_NOTAS INTO CURRENT 

    IF (CURRENT = NULL)
        THEN CURRENT := 0;
    END IF;

    OVERALL := OVERALL + CURRENT
    CHECK_PF := CHECK_PF + 1 
    IF (CHECK_PF = 2) THEN 
        PF := CURRENT 
        OVERALL := (OVERALL - CURRENT) / 2
    END IF;

EXIT WHEN NOT FOUND;

END LOOP;

UPDATE
    MATRICULA AS M
SET
    SITUACAO = (
        CASE 
            WHEN(OVERALL > 7 OR PF > 7) THEN 'APROVADO'
            WHEN ((OVERALL > 5 AND OVERALL < 7) OR PF > 5 AND PF < 7) THEN 'EM PROVA FINAL'
            ELSE 'REPROVADO'
        END AS SITUACAO
        )
    END;

$ $ LANGUAGE PLPGSQL;