-- UTILIZA O SCRIPT ABAIXO PARA CRIAR UMA SIMPLES TABELA DE ALUNOS
CREATE TABLE ALUNOS (
 MATRICULA SERIAL PRIMARY KEY,
 NOME VARCHAR(100),
 IDADE INT,
 UNIDADE VARCHAR(50)
 );

--  INSIRA UMA GRANDE QUANTIDADE DE DADOS NESSA TABELA PARA AS CONSULTAS COMEÇAREM
--  A FICAR MAIS PESADAS

 INSERT INTO ALUNOS (NOME, IDADE, UNIDADE)
 SELECT
 'ALUNO ' || GENERATE_SERIES(1, 9999),
 FLOOR(RANDOM() * 50) + 18,
 CASE FLOOR(RANDOM() * 3)
 WHEN 0 THEN 'MARIA DA GRAÇA'
 WHEN 1 THEN 'MARACANÃ'
 ELSE 'ANGRA'
 END
 FROM GENERATE_SERIES(1, 9999);


-- FAÇA UMA SIMPLES QUERY PARA VER O TEMPO DE EXECUÇÃO DA MESMA:

EXPLAIN SELECT * FROM ALUNOS AS A WHERE A.UNIDADE = 'MARACANÃ';

-- CRIE UM INDEX NA COLUNA QUE ESTÁ SENDO FEITO O WHERE

CREATE INDEX UNIDADE_INDEX ON ALUNOS(UNIDADE);

-- FAÇA A MESMA QUERY E VEJA O TEMPO DE EXECUÇÃO:

EXPLAIN SELECT * FROM ALUNOS AS A WHERE A.UNIDADE = 'MARACANÃ';