-- UTILIZA O SCRIPT ABAIXO PARA CRIAR UMA SIMPLES TABELA DE VENDAS
CREATE TABLE VENDAS (
 ID SERIAL PRIMARY KEY,
 DATA DATE,
 PRODUTO_ID INT,
 QUANTIDADE INT,
 VALOR_TOTAL DECIMAL(10, 2)
 );

--  INSIRA UMA GRANDE QUANTIDADE DE DADOS NESSA TABELA PARA AS CONSULTAS COMEÇAREM
--  A FICAR MAIS PESADAS

INSERT INTO VENDAS (DATA, PRODUTO_ID, QUANTIDADE, VALOR_TOTAL)
 SELECT
 '2024-01-01'::DATE + CAST(RANDOM() * (DATE '2024-03-31'-DATE
 '2024-01-01') AS INTEGER) AS DATA,
 FLOOR(RANDOM() * 1000) + 1 AS PRODUTO_ID,
 FLOOR(RANDOM() * 10) + 1 AS QUANTIDADE,
 ROUND(RANDOM()::NUMERIC * 1000, 2) AS VALOR_TOTAL
 FROM GENERATE_SERIES(1, 99999999);


-- FAÇA UMA SIMPLES QUERY PARA VER O TEMPO DE EXECUÇÃO DA MESMA:

EXPLAIN SELECT * FROM VENDAS AS V WHERE PRODUTO_ID = 180  AND DATA BETWEEN '2024-01-01' AND '2024-06-31'; 

-- CRIE UM INDEX COMPOSTO NAS COLUNAS QUE ESTÁ SENDO FEITO O WHERE

CREATE INDEX PROD_INDEX ON VENDAS(PRODUTO_ID, DATA);

-- FAÇA A MESMA QUERY E VEJA O TEMPO DE EXECUÇÃO:

EXPLAIN SELECT * FROM VENDAS AS V WHERE PRODUTO_ID = 180  AND DATA BETWEEN '2024-01-01' AND '2024-06-31'; 